version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./webapp/sql:/database
    ports:
      - 3306:3306
  app:
    image: golang:1.14
    environment:
      MYSQL_HOST: mysql
    volumes:
      - ./webapp/go:/app
    working_dir: /app
    command: go run main.go

